import { Session } from '../entities'

export interface SessionLoader {
  getSessionById(id: string): Promise<Session | null>
}

export interface SessionPersistor {
  // id is generated by the use case (not the DB) — it must be known before
  // creation so it can be embedded in the signed session token, and the
  // tokenHash (derived from that token) is what's actually persisted here.
  createSession(input: {
    id: string
    botId: string
    ipAddress: string
    userAgent?: string
    tokenHash: string
  }): Promise<Session>
  touchLastActivity(id: string): Promise<void>
  deleteSessionsByBotId(botId: string): Promise<void>
}
